


name: Build & Deploy Docker Images

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: camera_detect
            context: ./camera_detect/api_endpoint
            dockerfile: ./camera_detect/api_endpoint/Dockerfile
            image: haymannko/camera-detect
          - name: licence_ocr_rest
            context: ./licence_ocr/api_endpoint
            dockerfile: ./licence_ocr/api_endpoint/Dockerfile
            image: haymannko/licence-ocr-rest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ matrix.service.image }}:latest
            ${{ matrix.service.image }}:${{ github.sha }}

      - name: Run docker images
        run: docker images | grep ${{ matrix.service.image }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.service.image }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Confirm pushed image
        if: github.event_name == 'push'
        run: | 
          echo "Image pushed: ${{matrix.service.image}}:latest"
