

name: Build & Deploy Docker Image

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/banking-app
  IMAGE_TAG: latest

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build image but don't push on PRs
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }} # only push on merge (push to main)
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Confirm built image locally (works on both PR and push)
      - name: Run docker images
        run: docker images | grep ${{ env.IMAGE_NAME }}

      # Optional security scan step
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'   # change to '1' to fail pipeline if vulnerabilities found

      # Only login + push when it's a push (merge) event
      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Confirm pushed image
        if: github.event_name == 'push'
        run: |
          echo "Image pushed: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
